---
name: Black

on:
  pull_request:
    paths:
      - '**.py'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Check changed files
        id: changed-files
        uses: tj-actions/changed-files@v33
        with:
          files: '**/*.py'

      - name: Set up Python environment
        if: ${{ steps.changed-files.output.any_changed }} == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Black
        uses: psf/black@stable
        with:
          options: "--check --verbose --diff --color"
          src: ${{ steps.changed-files.outputs.all_changed_files }}
